### ISSUE TITLE
discord-butter 1.1 not working

### ISSUE THREAD

**Issue by Slashero** [ThaTiemsz/discord-butter#2]
Hi!
I just install the discord-butter rich presense and it didn't work.
This is the error I get:

"electron" is not recognized as an internal or external command, operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! discord-butter@1.0.1 start: `electron main.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the discord-butter@1.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

I'm very new with this, so idk how to fix it 
(I have installed node.js)

**Comment by ThaTiemsz** [comment]
Sorry, I forgot to add a step. Open a command prompt in the folder and run `npm install` first, which will install the required packages.

**Comment by Slashero** [comment]
Hi, thanks for answer :D 
When I try to install the required packages, the command prompt show me this error:

npm ERR! code ENOGIT
npm ERR! Error while executing:
npm ERR! undefined ls-remote -h -t ssh://git@github.com/discordjs/RPC.git
npm ERR!
npm ERR! undefined
npm ERR! No git binary found in $PATH
npm ERR!
npm ERR! Failed using git.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\pc\AppData\Roaming\npm-cache\_logs\2019-01-04T08_35_43_403Z-debug.log

**Comment by ThaTiemsz** [comment]
Install Git https://git-scm.com/downloads

**Comment by Slashero** [comment]
Thanks, I already fix that, but now the app say "Status: Not Connected"
In the console say:

Error: connect ECONNREFUSED 127.0.0.1:8008
       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1113:14)
     errno: 'ECONNREFUSED',
     code: 'ECONNREFUSED',
     syscall: 'connect',
     address: '127.0.0.1',
     port: 8008 },

**Comment by ThaTiemsz** [comment]
Go into Settings, check Show advanced settings, scroll down to Remote Control and make sure these settings are the same:

![image](https://user-images.githubusercontent.com/18150845/50729025-239ce580-1133-11e9-8139-e8ea20b3d33a.png)

**Comment by Slashero** [comment]
Thanks!! The problem was my Popcorn Time, it doesn't show up that options, now I download another and it work!
