### ISSUE TITLE
Status: Not connected

### ISSUE THREAD

**Issue by kevnthant** [ThaTiemsz/discord-butter#3]
After running this status not connected appears, how should i fix this

**Comment by ThaTiemsz** [comment]
Go to Settings in Popcorn Time, check Advanced Settings, go down to Remote Control, make sure the following settings are used:
- IP address: 127.0.0.1
- Port: 8008
- Username: popcorn
- Password: popcorn

**Comment by kevnthant** [comment]
I think its a different popcorntime youre using I'll download another one thank you.
